// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj3NXzhcNsHV_ReAfy8yMhqO_ao89w8pE',
    appId: '1:801354538085:web:62c0204d00c33b44ed7a8c',
    messagingSenderId: '801354538085',
    projectId: 'journal-1764b',
    authDomain: 'journal-1764b.firebaseapp.com',
    storageBucket: 'journal-1764b.firebasestorage.app',
    measurementId: 'G-WN7082H79P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfO6VcriRNjQGJVmTL8cfWZ1RBV4IpC9E',
    appId: '1:801354538085:android:fcfb1d79662754cced7a8c',
    messagingSenderId: '801354538085',
    projectId: 'journal-1764b',
    storageBucket: 'journal-1764b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlxJHOmn0q_0XR5_mMGzanQO7hcD9sFOU',
    appId: '1:801354538085:ios:bd55bf7aaaa0df58ed7a8c',
    messagingSenderId: '801354538085',
    projectId: 'journal-1764b',
    storageBucket: 'journal-1764b.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlxJHOmn0q_0XR5_mMGzanQO7hcD9sFOU',
    appId: '1:801354538085:ios:bd55bf7aaaa0df58ed7a8c',
    messagingSenderId: '801354538085',
    projectId: 'journal-1764b',
    storageBucket: 'journal-1764b.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDj3NXzhcNsHV_ReAfy8yMhqO_ao89w8pE',
    appId: '1:801354538085:web:45482762f5610881ed7a8c',
    messagingSenderId: '801354538085',
    projectId: 'journal-1764b',
    authDomain: 'journal-1764b.firebaseapp.com',
    storageBucket: 'journal-1764b.firebasestorage.app',
    measurementId: 'G-ND64HZ3S9P',
  );
}
